# version: "3.7"
services:
  # api:
  #   build:
  #     dockerfile: Dockerfile
  #     context: .
  #   command: "./bin/api"
  #   environment:
  #     - KAFKA_BROKERS=kafka:9092
  #   ports:
  #   - 8081:80
  #   depends_on:
  #   - kafka
  #   # - redis
  
  # process:
  #   build:
  #     dockerfile: Dockerfile
  #     context: .
  #   command: "./bin/process"
  #   environment:
  #   - KAFKA_BROKERS=kafka:9092
  #   depends_on:
  #   - kafka
  #   # - redis
  
  # kafka:
  #   image: docker.io/bitnami/kafka:2-debian-10
  # ports:
  #   - 9092:9092
  # environment:
  # - KAFKA_BROKER_ID=1
  # - KAFKA_LISTENERS=PLAINTEXT://:9092
  # - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
  # - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
  # - ALLOW_PLAINTEXT_LISTENER=yes
  # depends_on:
  # - zookeeper
  # healthcheck:
  #   test:
  #     ["CMD", "kafka-topics.sh", "--list", "--zookeeper", "zookeeper:2181"]
  #   interval: 30s
  #   timeout: 10s
  #   retries: 4

  # redis:
  #   image: redis:6.0
  #   ports:
  #     - 6379:6379

  # zookeeper:
  #   image: docker.io/bitnami/zookeeper:3-debian-10
  #   ports:
  #     - 2181:2181
  #   environment:
  #     - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      # - KAFKA_NODE_ID: 1
      # - KAFKA_PROCESS_ROLES: broker,controller
      # - KAFKA_LISTENERS: PLAINTEXT://localhost:9092,CONTROLLER://localhost:9093
      # - KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      # - KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      # - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      # - KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      # - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      # - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      # - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      # - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      # - KAFKA_NUM_PARTITIONS: 3

      - KAFKA_BROKER_ID:1
      - KAFKA_LISTENERS:PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS:PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT:ookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER:yes
      - KAFKA_PROCESS_ROLES:broker

    depends_on:
    - zookeeper      
  
  zookeeper:
    image: zookeeper:latest
    ports:
    - 2181:2181
    environment:
    - ALLOW_ANONYMOUS_LOGIN=yes