apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipo-slave
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: pipo-slave
  template:
    metadata:
      labels:
        app: pipo-slave
    spec:
      containers:
        - name: pipo-slave
          image: mypc.ru:5000/pipo:1.0.0
          imagePullPolicy: Always
          env:
          - name: PIPOMASTER
            value: "0"
          - name: PIPOSLAVENAME
            value: "pipo-slave"
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 1