apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  replicas: 2
  # strategy:
  #   type: RollingUpdate
    # rollingUpdate:
    #   maxUnavailable: 1
    #   maxSurge: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: apache/kafka:latest
          imagePullPolicy: Always
          env:
          - name: "KAFKA_NODE_ID"
            value: "1"
          - name: "KAFKA_PROCESS_ROLES"
            value: "broker,controller"
          - name: "KAFKA_LISTENERS"
            value: "PLAINTEXT://:9092,CONTROLLER://:9093"
          - name: "KAFKA_ADVERTISED_LISTENERS"
            value: "PLAINTEXT://kafka:9092"
          - name: "KAFKA_CONTROLLER_LISTENER_NAMES"
            value: "CONTROLLER"
          - name: "KAFKA_LISTENER_SECURITY_PROTOCOL_MAP"
            value: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
          - name: "KAFKA_CONTROLLER_QUORUM_VOTERS"
            value: "1@kafka:9093"
          - name: "KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR"
            value: "1"
          - name: "KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR"
            value: "1"
          - name: "KAFKA_TRANSACTION_STATE_LOG_MIN_ISR"
            value: "1"
          - name: "KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS"
            value: "0"
          - name: "KAFKA_NUM_PARTITIONS"
            value: "2"
          ports:
            - containerPort: 9092
            - containerPort: 9093
          readinessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 20
            periodSeconds: 15
            timeoutSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 20
            timeoutSeconds: 5