apiVersion: apps/v1
kind: Deployment
metadata:
  name: handlers
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: handlers
  template:
    metadata:
      labels:
        app: handlers
    spec:
      containers:
        - name: handlers
          image: mypc.ru:5000/handlers:1.0.7
          imagePullPolicy: Always
          env:
          - name: KAFKA_BROKERS
            value: "kafka:9092"
          - name: KAFKA_VERSION
            value: "4.0.0"
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /hc
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /hc
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 1